# Generated by Django 5.2.10 on 2026-01-31 09:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='campaign name')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='campaign name (Arabic)')),
                ('description', models.TextField(verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('num_emails', models.PositiveIntegerField(default=10, help_text='Total number of emails in the quiz (5-50)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='number of emails')),
                ('phishing_ratio', models.DecimalField(decimal_places=2, default=0.5, help_text='Ratio of phishing emails (0.2-0.8, e.g., 0.5 = 50%)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(0.8)], verbose_name='phishing email ratio')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, verbose_name='status')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('total_participants', models.PositiveIntegerField(default=0, verbose_name='total participants')),
                ('completed_participants', models.PositiveIntegerField(default=0, verbose_name='completed participants')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='average score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20, verbose_name='status')),
                ('current_question_index', models.PositiveIntegerField(default=0, verbose_name='current question index')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='campaigns.campaign', verbose_name='campaign')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(verbose_name='total questions')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='correct answers')),
                ('incorrect_answers', models.PositiveIntegerField(default=0, verbose_name='incorrect answers')),
                ('score', models.DecimalField(decimal_places=2, help_text='Score as percentage (0-100)', max_digits=5, verbose_name='score')),
                ('phishing_emails_identified', models.PositiveIntegerField(default=0, verbose_name='phishing emails correctly identified')),
                ('phishing_emails_missed', models.PositiveIntegerField(default=0, verbose_name='phishing emails missed')),
                ('false_positives', models.PositiveIntegerField(default=0, verbose_name='legitimate emails marked as phishing')),
                ('time_taken_seconds', models.PositiveIntegerField(help_text='Total time taken to complete the quiz in seconds', verbose_name='time taken (seconds)')),
                ('average_time_per_question', models.DecimalField(decimal_places=2, help_text='Average time per question in seconds', max_digits=6, verbose_name='average time per question')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='MEDIUM', max_length=20, verbose_name='risk level')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='completed at')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='campaigns.campaign', verbose_name='campaign')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='campaigns.quiz', verbose_name='quiz')),
            ],
            options={
                'verbose_name': 'quiz result',
                'verbose_name_plural': 'quiz results',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['company', 'status'], name='campaigns_c_company_ce8836_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'start_date'], name='campaigns_c_status_84323c_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['campaign', 'employee'], name='campaigns_q_campaig_86cdf4_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['status'], name='campaigns_q_status_4fb869_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('campaign', 'employee')},
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['employee', 'campaign'], name='campaigns_q_employe_fa9cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['risk_level'], name='campaigns_q_risk_le_1000c9_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['score'], name='campaigns_q_score_dd41b0_idx'),
        ),
    ]
