# Generated by Django 5.2.11 on 2026-02-23 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='english_ratio',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Ratio of English emails vs Arabic (0.0 to 1.0, e.g., 0.7 = 70% English)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='English email ratio'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='average_time_per_question',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Average time per question in seconds', max_digits=6, null=True, verbose_name='average time per question'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Total time taken to complete the quiz in seconds', null=True, verbose_name='time taken (seconds)'),
        ),
    ]
