# Generated by Django 5.2.11 on 2026-03-01 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TRAINING_ASSIGNED', 'Training Assigned'), ('TRAINING_DUE_SOON', 'Training Due Soon'), ('TRAINING_OVERDUE', 'Training Overdue'), ('SIMULATION_CLICKED', 'You Clicked Phishing Link'), ('SIMULATION_REPORTED', 'You Reported Phishing'), ('EMPLOYEE_CLICKED', 'Employee Clicked Phishing'), ('EMPLOYEE_REPORTED', 'Employee Reported Phishing'), ('CAMPAIGN_COMPLETED', 'Campaign Completed'), ('HIGH_RISK_ALERT', 'High Risk Employee'), ('TRAINING_COMPLETED', 'Training Completed'), ('NEW_COMPANY', 'New Company Registered'), ('SYSTEM_ALERT', 'System Alert')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
