# Generated by Django 5.2.10 on 2026-02-01 10:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='badge name')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='badge name (Arabic)')),
                ('badge_type', models.CharField(choices=[('FIRST_QUIZ_COMPLETED', 'First Quiz Completed'), ('PERFECT_QUIZ_SCORE', 'Perfect Quiz Score'), ('PHISH_SLAYER', 'Phish Slayer'), ('TRAINING_CHAMPION', 'Training Champion'), ('SECURITY_AWARE', 'Security Aware'), ('QUICK_LEARNER', 'Quick Learner'), ('SIMULATION_SURVIVOR', 'Simulation Survivor'), ('STREAK_MASTER', 'Streak Master'), ('TOP_REPORTER', 'Top Reporter')], max_length=30, unique=True, verbose_name='badge type')),
                ('description', models.TextField(verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('icon', models.CharField(help_text='Icon identifier or emoji for badge display', max_length=100, verbose_name='icon')),
                ('color', models.CharField(default='#FFD700', help_text='Hex color code for badge display', max_length=7, verbose_name='color')),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=20, verbose_name='rarity')),
                ('points_awarded', models.PositiveIntegerField(default=100, help_text='Points awarded when this badge is earned', validators=[django.core.validators.MinValueValidator(0)], verbose_name='points awarded')),
                ('criteria', models.JSONField(blank=True, default=dict, help_text='JSON criteria for badge awarding, e.g., {"quizzes_completed": 1}', verbose_name='criteria')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden badges are not shown until earned', verbose_name='is hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(blank=True, help_text='Leave empty for global badges', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'badge',
                'verbose_name_plural': 'badges',
                'ordering': ['rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='awarded at')),
                ('source_type', models.CharField(blank=True, help_text='Model that triggered this award (QuizResult, TrackingEvent, etc.)', max_length=50, verbose_name='source type')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='source ID')),
                ('points_awarded', models.PositiveIntegerField(default=0, verbose_name='points awarded')),
                ('is_notified', models.BooleanField(default=False, help_text='Whether user has been notified of this badge', verbose_name='user notified')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='notified at')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_badges', to='gamification.badge', verbose_name='badge')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_badges', to='companies.company', verbose_name='company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_badges', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
            options={
                'verbose_name': 'employee badge',
                'verbose_name_plural': 'employee badges',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='total points')),
                ('weekly_points', models.PositiveIntegerField(default=0, help_text='Points earned in current week', verbose_name='weekly points')),
                ('monthly_points', models.PositiveIntegerField(default=0, help_text='Points earned in current month', verbose_name='monthly points')),
                ('badge_count', models.PositiveIntegerField(default=0, verbose_name='badge count')),
                ('week_start', models.DateField(blank=True, null=True, verbose_name='week start')),
                ('month_start', models.DateField(blank=True, null=True, verbose_name='month start')),
                ('current_streak_days', models.PositiveIntegerField(default=0, verbose_name='current streak (days)')),
                ('longest_streak_days', models.PositiveIntegerField(default=0, verbose_name='longest streak (days)')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='last activity date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_points', to='companies.company', verbose_name='company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_points', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
            options={
                'verbose_name': 'employee points',
                'verbose_name_plural': 'employee points',
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('QUIZ_COMPLETED', 'Quiz Completed'), ('QUIZ_PERFECT_SCORE', 'Quiz Perfect Score'), ('PHISHING_REPORTED', 'Phishing Email Reported'), ('TRAINING_COMPLETED', 'Training Completed'), ('TRAINING_PASSED', 'Training Passed'), ('BADGE_EARNED', 'Badge Earned'), ('FIRST_ATTEMPT_PASS', 'First Attempt Pass'), ('STREAK_BONUS', 'Streak Bonus'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('BONUS', 'Bonus Award')], max_length=30, verbose_name='transaction type')),
                ('points', models.IntegerField(help_text='Positive for earned, negative for deductions', verbose_name='points')),
                ('balance_after', models.PositiveIntegerField(default=0, verbose_name='balance after')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('description_ar', models.CharField(blank=True, max_length=255, verbose_name='description (Arabic)')),
                ('source_type', models.CharField(blank=True, max_length=50, verbose_name='source type')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='source ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='companies.company', verbose_name='company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
            options={
                'verbose_name': 'points transaction',
                'verbose_name_plural': 'points transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['badge_type', 'is_active'], name='gamificatio_badge_t_6bd4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['company', 'is_active'], name='gamificatio_company_d62909_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebadge',
            index=models.Index(fields=['employee', '-awarded_at'], name='gamificatio_employe_ef929c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebadge',
            index=models.Index(fields=['company', '-awarded_at'], name='gamificatio_company_0cdbc7_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebadge',
            index=models.Index(fields=['badge', '-awarded_at'], name='gamificatio_badge_i_591bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebadge',
            index=models.Index(fields=['is_notified'], name='gamificatio_is_noti_c6dd38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeebadge',
            unique_together={('employee', 'badge')},
        ),
        migrations.AddIndex(
            model_name='employeepoints',
            index=models.Index(fields=['company', '-total_points'], name='gamificatio_company_60d808_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepoints',
            index=models.Index(fields=['company', '-weekly_points'], name='gamificatio_company_a27ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepoints',
            index=models.Index(fields=['company', '-monthly_points'], name='gamificatio_company_16e961_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['employee', '-created_at'], name='gamificatio_employe_edc3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['company', '-created_at'], name='gamificatio_company_e4ff9a_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['transaction_type'], name='gamificatio_transac_9dad6f_idx'),
        ),
    ]
