# Generated by Django 5.2.10 on 2026-02-01 11:08

from django.db import migrations


INITIAL_BADGES = [
    {
        'name': 'First Quiz Completed',
        'name_ar': 'اختبار أول مكتمل',
        'badge_type': 'FIRST_QUIZ_COMPLETED',
        'description': 'Completed your first phishing awareness quiz',
        'description_ar': 'أكملت اختبارك الأول للتوعية بالتصيد',
        'icon': 'trophy',
        'color': '#4CAF50',
        'rarity': 'COMMON',
        'points_awarded': 50,
        'criteria': {'quizzes_completed': 1},
        'is_active': True,
        'is_hidden': False,
    },
    {
        'name': 'Perfect Quiz Score',
        'name_ar': 'درجة اختبار مثالية',
        'badge_type': 'PERFECT_QUIZ_SCORE',
        'description': 'Achieved 100% on a phishing awareness quiz',
        'description_ar': 'حققت 100% في اختبار التوعية بالتصيد',
        'icon': 'star',
        'color': '#FFD700',
        'rarity': 'RARE',
        'points_awarded': 100,
        'criteria': {'quiz_score': 100},
        'is_active': True,
        'is_hidden': False,
    },
    {
        'name': 'Phish Slayer',
        'name_ar': 'قاتل التصيد',
        'badge_type': 'PHISH_SLAYER',
        'description': 'Reported 5 or more phishing simulation emails',
        'description_ar': 'أبلغت عن 5 رسائل محاكاة تصيد أو أكثر',
        'icon': 'shield',
        'color': '#2196F3',
        'rarity': 'UNCOMMON',
        'points_awarded': 150,
        'criteria': {'phishing_reported': 5},
        'is_active': True,
        'is_hidden': False,
    },
    {
        'name': 'Training Champion',
        'name_ar': 'بطل التدريب',
        'badge_type': 'TRAINING_CHAMPION',
        'description': 'Completed all assigned security trainings',
        'description_ar': 'أكملت جميع التدريبات الأمنية المعينة',
        'icon': 'award',
        'color': '#9C27B0',
        'rarity': 'EPIC',
        'points_awarded': 200,
        'criteria': {'all_trainings_completed': True},
        'is_active': True,
        'is_hidden': False,
    },
    {
        'name': 'Security Aware',
        'name_ar': 'واعي أمنياً',
        'badge_type': 'SECURITY_AWARE',
        'description': 'Maintained LOW risk score for 30 consecutive days',
        'description_ar': 'حافظت على درجة مخاطر منخفضة لمدة 30 يوماً متتالية',
        'icon': 'verified',
        'color': '#00BCD4',
        'rarity': 'LEGENDARY',
        'points_awarded': 300,
        'criteria': {'low_risk_days': 30},
        'is_active': True,
        'is_hidden': False,
    },
    {
        'name': 'Quick Learner',
        'name_ar': 'متعلم سريع',
        'badge_type': 'QUICK_LEARNER',
        'description': 'Passed a training quiz on the first attempt',
        'description_ar': 'اجتزت اختبار التدريب من المحاولة الأولى',
        'icon': 'bolt',
        'color': '#FF9800',
        'rarity': 'UNCOMMON',
        'points_awarded': 75,
        'criteria': {'first_attempt_pass': True},
        'is_active': True,
        'is_hidden': False,
    },
]


def create_initial_badges(apps, schema_editor):
    """Create initial badge definitions."""
    Badge = apps.get_model('gamification', 'Badge')

    for badge_data in INITIAL_BADGES:
        Badge.objects.get_or_create(
            badge_type=badge_data['badge_type'],
            defaults=badge_data
        )


def remove_initial_badges(apps, schema_editor):
    """Remove initial badges (reverse migration)."""
    Badge = apps.get_model('gamification', 'Badge')
    badge_types = [b['badge_type'] for b in INITIAL_BADGES]
    Badge.objects.filter(badge_type__in=badge_types).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_badges, remove_initial_badges),
    ]
