# Generated by Django 5.2.11 on 2026-02-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores breakdown details, e.g. {"quiz_score": 80, "base_points": 50, "performance_bonus": 40}', verbose_name='metadata'),
        ),
    ]
