# Generated by Django 5.2.10 on 2026-01-31 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='campaign name')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='campaign name (Arabic)')),
                ('description', models.TextField(verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='status')),
                ('send_date', models.DateTimeField(blank=True, help_text='When to send the simulation emails', null=True, verbose_name='scheduled send date')),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop tracking and close the simulation', null=True, verbose_name='end date')),
                ('target_all_employees', models.BooleanField(default=False, help_text='If true, send to all employees in the company', verbose_name='target all employees')),
                ('track_email_opens', models.BooleanField(default=True, verbose_name='track email opens')),
                ('track_link_clicks', models.BooleanField(default=True, verbose_name='track link clicks')),
                ('track_credentials', models.BooleanField(default=False, help_text='If true, landing page includes fake login form', verbose_name='track credential entry')),
                ('notify_on_click', models.BooleanField(default=False, help_text='Send notification to admin when employee clicks link', verbose_name='notify admin on click')),
                ('notify_on_credential_entry', models.BooleanField(default=True, verbose_name='notify admin on credential entry')),
                ('total_sent', models.PositiveIntegerField(default=0, verbose_name='total emails sent')),
                ('total_delivered', models.PositiveIntegerField(default=0, verbose_name='total delivered')),
                ('total_opened', models.PositiveIntegerField(default=0, verbose_name='total opened')),
                ('total_clicked', models.PositiveIntegerField(default=0, verbose_name='total clicked')),
                ('total_reported', models.PositiveIntegerField(default=0, help_text='Number of employees who reported the email as phishing', verbose_name='total reported')),
                ('total_credentials_entered', models.PositiveIntegerField(default=0, verbose_name='credentials entered')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_campaigns', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_simulation_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('target_employees', models.ManyToManyField(blank=True, limit_choices_to={'role': 'EMPLOYEE'}, related_name='targeted_in_simulations', to=settings.AUTH_USER_MODEL, verbose_name='target employees')),
            ],
            options={
                'verbose_name': 'simulation campaign',
                'verbose_name_plural': 'simulation campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for tracking this specific email', unique=True, verbose_name='tracking token')),
                ('link_token', models.CharField(editable=False, help_text='Unique token for the phishing link', max_length=64, unique=True, verbose_name='link token')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='recipient email')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('BOUNCED', 'Bounced'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='status')),
                ('was_opened', models.BooleanField(default=False, verbose_name='email opened')),
                ('was_clicked', models.BooleanField(default=False, verbose_name='link clicked')),
                ('was_reported', models.BooleanField(default=False, help_text='Employee reported this email as phishing (good!)', verbose_name='reported as phishing')),
                ('credentials_entered', models.BooleanField(default=False, verbose_name='credentials entered')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('first_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='first opened at')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='clicked at')),
                ('reported_at', models.DateTimeField(blank=True, null=True, verbose_name='reported at')),
                ('credentials_entered_at', models.DateTimeField(blank=True, null=True, verbose_name='credentials entered at')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the link was clicked', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information when link was clicked', verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_simulations', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_simulations', to='simulations.simulationcampaign', verbose_name='campaign')),
            ],
            options={
                'verbose_name': 'email simulation',
                'verbose_name_plural': 'email simulations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='template name')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='template name (Arabic)')),
                ('description', models.TextField(verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('sender_name', models.CharField(max_length=255, verbose_name='sender name')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='sender email')),
                ('reply_to_email', models.EmailField(blank=True, max_length=254, verbose_name='reply-to email')),
                ('subject', models.CharField(max_length=500, verbose_name='email subject')),
                ('body_html', models.TextField(verbose_name='email body (HTML)')),
                ('body_plain', models.TextField(blank=True, verbose_name='email body (Plain Text)')),
                ('attack_vector', models.CharField(choices=[('LINK_MANIPULATION', 'Malicious Link'), ('CREDENTIAL_HARVESTING', 'Fake Login Page'), ('ATTACHMENT_MALWARE', 'Malicious Attachment'), ('URGENCY_SCAM', 'Urgency/Fear Tactics'), ('AUTHORITY_IMPERSONATION', 'Authority Figure Impersonation'), ('PRIZE_LOTTERY', 'Prize/Lottery Scam'), ('BUSINESS_EMAIL_COMPROMISE', 'Business Email Compromise')], max_length=50, verbose_name='attack vector')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy - Obvious indicators'), ('MEDIUM', 'Medium - Some subtle indicators'), ('HARD', 'Hard - Very convincing'), ('EXPERT', 'Expert - Nearly identical to legitimate')], default='MEDIUM', max_length=10, verbose_name='difficulty level')),
                ('requires_landing_page', models.BooleanField(default=True, help_text='If true, clicked links redirect to educational landing page', verbose_name='requires landing page')),
                ('landing_page_title', models.CharField(blank=True, max_length=255, verbose_name='landing page title')),
                ('landing_page_message', models.TextField(blank=True, help_text='Educational message shown when employee clicks the phishing link', verbose_name='landing page message')),
                ('landing_page_message_ar', models.TextField(blank=True, verbose_name='landing page message (Arabic)')),
                ('red_flags', models.JSONField(default=list, help_text='List of indicators that reveal this is a phishing attempt', verbose_name='phishing red flags')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_public', models.BooleanField(default=False, help_text='If true, available to all companies in the platform', verbose_name='public template')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2, verbose_name='language')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='times used')),
                ('average_click_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Average percentage of employees who click the link', max_digits=5, null=True, verbose_name='average click rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(blank=True, help_text='Leave empty for global templates available to all companies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_templates', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_simulation_templates', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'simulation template',
                'verbose_name_plural': 'simulation templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='simulationcampaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='simulations.simulationtemplate', verbose_name='email template'),
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('EMAIL_SENT', 'Email Sent'), ('EMAIL_DELIVERED', 'Email Delivered'), ('EMAIL_BOUNCED', 'Email Bounced'), ('EMAIL_OPENED', 'Email Opened'), ('LINK_CLICKED', 'Link Clicked'), ('CREDENTIALS_ENTERED', 'Credentials Entered'), ('EMAIL_REPORTED', 'Email Reported as Phishing'), ('LANDING_PAGE_VIEWED', 'Landing Page Viewed')], max_length=30, verbose_name='event type')),
                ('event_data', models.JSONField(blank=True, default=dict, help_text='Additional data about the event (e.g., form data, click location)', verbose_name='event data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('geolocation', models.JSONField(blank=True, default=dict, help_text='Geolocation data from IP address', verbose_name='geolocation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='simulations.simulationcampaign', verbose_name='campaign')),
                ('email_simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='simulations.emailsimulation', verbose_name='email simulation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_events', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
            options={
                'verbose_name': 'tracking event',
                'verbose_name_plural': 'tracking events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailsimulation',
            index=models.Index(fields=['campaign', 'employee'], name='simulations_campaig_933155_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsimulation',
            index=models.Index(fields=['tracking_token'], name='simulations_trackin_ea836f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsimulation',
            index=models.Index(fields=['link_token'], name='simulations_link_to_d61b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsimulation',
            index=models.Index(fields=['was_clicked', 'credentials_entered'], name='simulations_was_cli_6a4588_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailsimulation',
            unique_together={('campaign', 'employee')},
        ),
        migrations.AddIndex(
            model_name='simulationtemplate',
            index=models.Index(fields=['attack_vector', 'difficulty'], name='simulations_attack__b3206f_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationtemplate',
            index=models.Index(fields=['is_active', 'is_public'], name='simulations_is_acti_8ae691_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationcampaign',
            index=models.Index(fields=['company', 'status'], name='simulations_company_4f9b27_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationcampaign',
            index=models.Index(fields=['status', 'send_date'], name='simulations_status_34af1d_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['email_simulation', 'event_type'], name='simulations_email_s_4ea254_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['campaign', 'event_type'], name='simulations_campaig_c88a05_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['employee', 'created_at'], name='simulations_employe_11eda3_idx'),
        ),
    ]
