# Generated by Django 5.2.11 on 2026-02-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_quizquestion_selected_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='flag_max_score',
            field=models.IntegerField(default=0, help_text='Maximum possible points from red flags for this question', verbose_name='flag max score'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='flag_score',
            field=models.IntegerField(default=0, help_text='Points earned from red flag selections (correct flags minus penalties)', verbose_name='flag score'),
        ),
    ]
