# Generated by Django 5.2.10 on 2026-01-31 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='company name')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='company name (Arabic)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('email', models.EmailField(max_length=254, verbose_name='company email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('website', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='website')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('industry', models.CharField(choices=[('TECH', 'Technology'), ('FINANCE', 'Finance & Banking'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('RETAIL', 'Retail & E-commerce'), ('MANUFACTURING', 'Manufacturing'), ('GOVERNMENT', 'Government'), ('TELECOM', 'Telecommunications'), ('ENERGY', 'Energy & Utilities'), ('OTHER', 'Other')], max_length=50, verbose_name='industry')),
                ('company_size', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1001+', '1001+ employees')], max_length=20, verbose_name='company size')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('subscription_start_date', models.DateField(blank=True, null=True, verbose_name='subscription start date')),
                ('subscription_end_date', models.DateField(blank=True, null=True, verbose_name='subscription end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='companies_c_name_2d8260_idx'), models.Index(fields=['is_active'], name='companies_c_is_acti_03043b_idx')],
            },
        ),
    ]
