# Generated by Django 5.2.11 on 2026-03-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TRAINING_ASSIGNED', 'Training Assigned'), ('TRAINING_DUE_SOON', 'Training Due Soon'), ('TRAINING_DUE_TOMORROW', 'Training Due Tomorrow'), ('TRAINING_OVERDUE', 'Training Overdue'), ('TRAINING_COMPLETED_EMPLOYEE', 'Training Completed - You'), ('QUIZ_FAILED', 'Quiz Failed'), ('QUIZ_PASSED', 'Quiz Passed'), ('SIMULATION_CLICKED', 'You Clicked Phishing Link'), ('SIMULATION_REPORTED', 'You Reported Phishing'), ('SIMULATION_LAUNCHED', 'New Simulation Campaign'), ('SIMULATION_SAFE', 'Simulation Expired - You Were Safe'), ('WELCOME', 'Welcome to PhishAware'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('SECURITY_SCORE_UP', 'Security Score Improved'), ('SECURITY_SCORE_DOWN', 'Security Score Decreased'), ('EMPLOYEE_CLICKED', 'Employee Clicked Phishing'), ('EMPLOYEE_REPORTED', 'Employee Reported Phishing'), ('TRAINING_COMPLETED', 'Training Completed'), ('EMPLOYEE_FAILED_QUIZ', 'Employee Failed Training'), ('MULTIPLE_FAILURES', 'Multiple Employees Failed'), ('HIGH_RISK_EMPLOYEE', 'Employee Marked High Risk'), ('CAMPAIGN_COMPLETED', 'Campaign Completed'), ('SIMULATION_PROGRESS', 'Simulation Progress Update'), ('HIGH_CLICK_RATE', 'High Click Rate Alert'), ('LOW_REPORT_RATE', 'Low Report Rate Warning'), ('SIMULATION_SENT', 'Simulation Emails Sent'), ('TRAINING_DEADLINE_APPROACHING', 'Training Deadlines Approaching'), ('OVERDUE_TRAININGS', 'Overdue Trainings Alert'), ('MONTHLY_REPORT_READY', 'Monthly Report Ready'), ('EMPLOYEE_JOINED', 'New Employee Joined'), ('INVITATION_EXPIRED', 'Employee Invitation Expired'), ('HIGH_RISK_ALERT', 'High Risk Employee'), ('NEW_COMPANY', 'New Company Registered'), ('SYSTEM_ALERT', 'System Alert'), ('BACKUP_COMPLETED', 'Backup Completed')], max_length=50),
        ),
    ]
