# Generated by Django 5.2.10 on 2026-01-31 22:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=50, help_text='Risk score from 0 (safest) to 100 (most at risk)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='risk score')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='MEDIUM', max_length=20, verbose_name='risk level')),
                ('total_quizzes_taken', models.PositiveIntegerField(default=0, verbose_name='total quizzes taken')),
                ('total_quiz_questions', models.PositiveIntegerField(default=0, verbose_name='total quiz questions')),
                ('correct_quiz_answers', models.PositiveIntegerField(default=0, verbose_name='correct quiz answers')),
                ('phishing_emails_missed', models.PositiveIntegerField(default=0, verbose_name='phishing emails missed')),
                ('total_simulations_received', models.PositiveIntegerField(default=0, verbose_name='total simulations received')),
                ('simulations_opened', models.PositiveIntegerField(default=0, verbose_name='simulations opened')),
                ('simulations_clicked', models.PositiveIntegerField(default=0, verbose_name='simulations clicked')),
                ('simulations_reported', models.PositiveIntegerField(default=0, verbose_name='simulations reported')),
                ('credentials_entered', models.PositiveIntegerField(default=0, verbose_name='credentials entered')),
                ('trainings_assigned', models.PositiveIntegerField(default=0, verbose_name='trainings assigned')),
                ('trainings_completed', models.PositiveIntegerField(default=0, verbose_name='trainings completed')),
                ('trainings_passed', models.PositiveIntegerField(default=0, verbose_name='trainings passed')),
                ('requires_remediation', models.BooleanField(default=False, help_text='Auto-set when score exceeds threshold', verbose_name='requires remediation')),
                ('last_quiz_date', models.DateTimeField(blank=True, null=True, verbose_name='last quiz date')),
                ('last_simulation_date', models.DateTimeField(blank=True, null=True, verbose_name='last simulation date')),
                ('last_training_date', models.DateTimeField(blank=True, null=True, verbose_name='last training date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_risk_scores', to='companies.company', verbose_name='company')),
                ('employee', models.OneToOneField(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='risk_score', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
            options={
                'verbose_name': 'risk score',
                'verbose_name_plural': 'risk scores',
                'ordering': ['-score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('QUIZ_COMPLETED', 'Quiz Completed'), ('QUIZ_FAILED', 'Quiz Failed'), ('SIMULATION_OPENED', 'Simulation Opened'), ('SIMULATION_CLICKED', 'Simulation Clicked'), ('CREDENTIALS_ENTERED', 'Credentials Entered'), ('PHISHING_REPORTED', 'Phishing Reported'), ('TRAINING_ASSIGNED', 'Training Assigned'), ('TRAINING_COMPLETED', 'Training Completed'), ('TRAINING_PASSED', 'Training Passed'), ('TRAINING_FAILED', 'Training Failed'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('SCORE_RECALCULATED', 'Score Recalculated')], max_length=30, verbose_name='event type')),
                ('previous_score', models.IntegerField(verbose_name='previous score')),
                ('new_score', models.IntegerField(verbose_name='new score')),
                ('score_change', models.IntegerField(verbose_name='score change')),
                ('previous_risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], max_length=20, verbose_name='previous risk level')),
                ('new_risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], max_length=20, verbose_name='new risk level')),
                ('source_type', models.CharField(blank=True, help_text='Model that triggered this change (e.g., QuizResult, TrackingEvent)', max_length=50, verbose_name='source type')),
                ('source_id', models.PositiveIntegerField(blank=True, help_text='ID of the source object', null=True, verbose_name='source ID')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of what caused the change', verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score_history', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('risk_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='training.riskscore', verbose_name='risk score')),
            ],
            options={
                'verbose_name': 'risk score history',
                'verbose_name_plural': 'risk score histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_ar', models.CharField(blank=True, max_length=255, verbose_name='title (Arabic)')),
                ('description', models.TextField(verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video'), ('TEXT', 'Text Article'), ('INTERACTIVE', 'Interactive Tutorial'), ('PDF', 'PDF Document'), ('SLIDES', 'Presentation Slides')], default='TEXT', max_length=20, verbose_name='content type')),
                ('category', models.CharField(choices=[('PHISHING_BASICS', 'Phishing Basics'), ('EMAIL_SECURITY', 'Email Security'), ('LINK_SAFETY', 'Link Safety'), ('CREDENTIAL_PROTECTION', 'Credential Protection'), ('SOCIAL_ENGINEERING', 'Social Engineering'), ('REPORTING_PROCEDURES', 'Reporting Procedures'), ('PASSWORD_SECURITY', 'Password Security'), ('DATA_PROTECTION', 'Data Protection'), ('MOBILE_SECURITY', 'Mobile Security'), ('GENERAL_AWARENESS', 'General Security Awareness')], default='GENERAL_AWARENESS', max_length=30, verbose_name='category')),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20, verbose_name='difficulty')),
                ('content_html', models.TextField(help_text='Training content in HTML format', verbose_name='content (HTML)')),
                ('content_html_ar', models.TextField(blank=True, verbose_name='content (HTML - Arabic)')),
                ('video_url', models.URLField(blank=True, help_text='URL for video content (YouTube, Vimeo, etc.)', verbose_name='video URL')),
                ('duration_minutes', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='duration (minutes)')),
                ('passing_score', models.PositiveIntegerField(default=80, help_text='Minimum percentage required to pass', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='passing score')),
                ('min_questions_required', models.PositiveIntegerField(default=5, help_text='Number of questions in post-training quiz', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='minimum questions required')),
                ('score_reduction_on_pass', models.PositiveIntegerField(default=15, help_text='Points to reduce from risk score when training is passed', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)], verbose_name='score reduction on pass')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_mandatory', models.BooleanField(default=False, help_text='If true, this training is required for all high-risk employees', verbose_name='is mandatory')),
                ('times_assigned', models.PositiveIntegerField(default=0, verbose_name='times assigned')),
                ('times_completed', models.PositiveIntegerField(default=0, verbose_name='times completed')),
                ('times_passed', models.PositiveIntegerField(default=0, verbose_name='times passed')),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='average score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(blank=True, help_text='Leave empty for global training modules', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_modules', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_modules', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'training module',
                'verbose_name_plural': 'training modules',
                'ordering': ['category', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RemediationTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='ASSIGNED', max_length=20, verbose_name='status')),
                ('assignment_reason', models.CharField(choices=[('AUTO_HIGH_RISK', 'Auto-assigned: High Risk Score'), ('AUTO_SIMULATION_FAIL', 'Auto-assigned: Simulation Failure'), ('AUTO_QUIZ_FAIL', 'Auto-assigned: Quiz Failure'), ('MANUAL_ADMIN', 'Manually Assigned by Admin'), ('MANDATORY', 'Mandatory Training'), ('REFRESHER', 'Refresher Training')], default='MANUAL_ADMIN', max_length=30, verbose_name='assignment reason')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('due_date', models.DateTimeField(blank=True, help_text='Deadline for completion', null=True, verbose_name='due date')),
                ('quiz_attempts', models.PositiveIntegerField(default=0, verbose_name='quiz attempts')),
                ('quiz_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='quiz score')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='correct answers')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='total questions')),
                ('content_viewed', models.BooleanField(default=False, verbose_name='content viewed')),
                ('content_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='content viewed at')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='time spent (seconds)')),
                ('risk_score_before', models.IntegerField(blank=True, null=True, verbose_name='risk score before')),
                ('risk_score_after', models.IntegerField(blank=True, null=True, verbose_name='risk score after')),
                ('source_type', models.CharField(blank=True, help_text='What triggered this assignment (QuizResult, TrackingEvent, etc.)', max_length=50, verbose_name='source type')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='source ID')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who assigned. Null if auto-assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trainings', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_trainings', to='companies.company', verbose_name='company')),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='remediation_trainings', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('training_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='training.trainingmodule', verbose_name='training module')),
            ],
            options={
                'verbose_name': 'remediation training',
                'verbose_name_plural': 'remediation trainings',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(default=1, verbose_name='question number')),
                ('question_text', models.TextField(verbose_name='question text')),
                ('question_text_ar', models.TextField(blank=True, verbose_name='question text (Arabic)')),
                ('options', models.JSONField(default=list, help_text='List of answer options, e.g., ["Option A", "Option B", "Option C", "Option D"]', verbose_name='options')),
                ('options_ar', models.JSONField(blank=True, default=list, verbose_name='options (Arabic)')),
                ('correct_answer_index', models.PositiveIntegerField(help_text='Index of correct answer (0-3)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='correct answer index')),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering', verbose_name='explanation')),
                ('explanation_ar', models.TextField(blank=True, verbose_name='explanation (Arabic)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='training.trainingmodule', verbose_name='training module')),
            ],
            options={
                'verbose_name': 'training question',
                'verbose_name_plural': 'training questions',
                'ordering': ['module', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='TrainingQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer_index', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='selected answer index')),
                ('is_correct', models.BooleanField(verbose_name='is correct')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='answered at')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='time spent (seconds)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='training.trainingquestion', verbose_name='question')),
                ('remediation_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='training.remediationtraining', verbose_name='remediation training')),
            ],
            options={
                'verbose_name': 'training quiz answer',
                'verbose_name_plural': 'training quiz answers',
                'ordering': ['remediation_training', 'question__question_number'],
            },
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['company', 'risk_level'], name='training_ri_company_95d6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['score'], name='training_ri_score_b60406_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['requires_remediation'], name='training_ri_require_97650e_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscorehistory',
            index=models.Index(fields=['risk_score', '-created_at'], name='training_ri_risk_sc_61a07f_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscorehistory',
            index=models.Index(fields=['employee', '-created_at'], name='training_ri_employe_1f9c10_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscorehistory',
            index=models.Index(fields=['event_type'], name='training_ri_event_t_acbf45_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmodule',
            index=models.Index(fields=['category', 'is_active'], name='training_tr_categor_fd1628_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmodule',
            index=models.Index(fields=['difficulty'], name='training_tr_difficu_acb6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmodule',
            index=models.Index(fields=['company', 'is_active'], name='training_tr_company_ee8308_idx'),
        ),
        migrations.AddIndex(
            model_name='remediationtraining',
            index=models.Index(fields=['employee', 'status'], name='training_re_employe_0b7c90_idx'),
        ),
        migrations.AddIndex(
            model_name='remediationtraining',
            index=models.Index(fields=['company', 'status'], name='training_re_company_7692ce_idx'),
        ),
        migrations.AddIndex(
            model_name='remediationtraining',
            index=models.Index(fields=['training_module', 'status'], name='training_re_trainin_e72c24_idx'),
        ),
        migrations.AddIndex(
            model_name='remediationtraining',
            index=models.Index(fields=['due_date'], name='training_re_due_dat_61dfef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingquestion',
            unique_together={('module', 'question_number')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingquizanswer',
            unique_together={('remediation_training', 'question')},
        ),
    ]
