# Generated by Django 5.2.10 on 2026-01-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255, verbose_name='sender name')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='sender email')),
                ('subject', models.CharField(max_length=500, verbose_name='subject')),
                ('body', models.TextField(verbose_name='email body')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='has attachments')),
                ('attachment_names', models.JSONField(blank=True, default=list, help_text='List of fake attachment names for display', verbose_name='attachment names')),
                ('links', models.JSONField(blank=True, default=list, help_text='List of links in the email', verbose_name='links')),
                ('email_type', models.CharField(choices=[('PHISHING', 'Phishing Email'), ('LEGITIMATE', 'Legitimate Email')], max_length=20, verbose_name='email type')),
                ('category', models.CharField(choices=[('SPEAR_PHISHING', 'Spear Phishing'), ('WHALING', 'Whaling'), ('CLONE_PHISHING', 'Clone Phishing'), ('BUSINESS_EMAIL_COMPROMISE', 'Business Email Compromise'), ('LINK_MANIPULATION', 'Link Manipulation'), ('CREDENTIAL_HARVESTING', 'Credential Harvesting'), ('MALWARE_ATTACHMENT', 'Malware Attachment'), ('LEGITIMATE_BUSINESS', 'Legitimate Business Email'), ('LEGITIMATE_PERSONAL', 'Legitimate Personal Email'), ('LEGITIMATE_NOTIFICATION', 'Legitimate Notification')], help_text='Specific phishing technique or legitimate email type', max_length=50, verbose_name='category')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10, verbose_name='difficulty level')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='AI generated')),
                ('ai_model_used', models.CharField(blank=True, help_text='Name of the AI model used for generation', max_length=100, verbose_name='AI model used')),
                ('generation_prompt', models.TextField(blank=True, help_text='Prompt used to generate this email', verbose_name='generation prompt')),
                ('red_flags', models.JSONField(blank=True, default=list, help_text='List of phishing indicators in this email', verbose_name='red flags')),
                ('explanation', models.TextField(blank=True, help_text="Detailed explanation of why this is/isn't phishing", verbose_name='explanation')),
                ('explanation_ar', models.TextField(blank=True, verbose_name='explanation (Arabic)')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2, verbose_name='language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(help_text='Order of this question in the quiz', verbose_name='question number')),
                ('answer', models.CharField(blank=True, choices=[('PHISHING', 'Phishing'), ('LEGITIMATE', 'Legitimate')], max_length=20, null=True, verbose_name='employee answer')),
                ('is_correct', models.BooleanField(blank=True, help_text="Whether the employee's answer is correct", null=True, verbose_name='is correct')),
                ('confidence_level', models.PositiveIntegerField(blank=True, help_text='Employee confidence in their answer (1-5)', null=True, verbose_name='confidence level')),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, help_text='Time spent on this question', null=True, verbose_name='time spent (seconds)')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='answered at')),
                ('requires_training', models.BooleanField(default=False, help_text='Flag if employee needs additional training on this type', verbose_name='requires training')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'quiz question',
                'verbose_name_plural': 'quiz questions',
                'ordering': ['quiz', 'question_number'],
            },
        ),
    ]
