from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _


class EmailTemplate(models.Model):
    """
    EmailTemplate model for storing both phishing and legitimate emails.

    These emails are used in quiz campaigns. Can be either manually created
    or generated by AI.
    """

    EMAIL_TYPE_CHOICES = [
        ('PHISHING', _('Phishing Email')),
        ('LEGITIMATE', _('Legitimate Email')),
    ]

    CATEGORY_CHOICES = [
        ('SPEAR_PHISHING', _('Spear Phishing')),
        ('WHALING', _('Whaling')),
        ('CLONE_PHISHING', _('Clone Phishing')),
        ('BUSINESS_EMAIL_COMPROMISE', _('Business Email Compromise')),
        ('LINK_MANIPULATION', _('Link Manipulation')),
        ('CREDENTIAL_HARVESTING', _('Credential Harvesting')),
        ('MALWARE_ATTACHMENT', _('Malware Attachment')),
        ('LEGITIMATE_BUSINESS', _('Legitimate Business Email')),
        ('LEGITIMATE_PERSONAL', _('Legitimate Personal Email')),
        ('LEGITIMATE_NOTIFICATION', _('Legitimate Notification')),
    ]

    DIFFICULTY_CHOICES = [
        ('EASY', _('Easy')),
        ('MEDIUM', _('Medium')),
        ('HARD', _('Hard')),
    ]

    # Relationships
    campaign = models.ForeignKey(
        'campaigns.Campaign',
        on_delete=models.CASCADE,
        related_name='email_templates',
        verbose_name=_('campaign')
    )

    # Email Content
    sender_name = models.CharField(_('sender name'), max_length=255)
    sender_email = models.EmailField(_('sender email'))
    subject = models.CharField(_('subject'), max_length=500)
    body = models.TextField(_('email body'))

    # Optional attachments/links (for display purposes)
    has_attachments = models.BooleanField(_('has attachments'), default=False)
    attachment_names = models.JSONField(
        _('attachment names'),
        default=list,
        blank=True,
        help_text=_('List of fake attachment names for display')
    )
    links = models.JSONField(
        _('links'),
        default=list,
        blank=True,
        help_text=_('List of links in the email')
    )

    # Classification
    email_type = models.CharField(
        _('email type'),
        max_length=20,
        choices=EMAIL_TYPE_CHOICES
    )
    category = models.CharField(
        _('category'),
        max_length=50,
        choices=CATEGORY_CHOICES,
        help_text=_('Specific phishing technique or legitimate email type')
    )
    difficulty = models.CharField(
        _('difficulty level'),
        max_length=10,
        choices=DIFFICULTY_CHOICES,
        default='MEDIUM'
    )

    # AI Generation
    is_ai_generated = models.BooleanField(_('AI generated'), default=False)
    ai_model_used = models.CharField(
        _('AI model used'),
        max_length=100,
        blank=True,
        help_text=_('Name of the AI model used for generation')
    )
    generation_prompt = models.TextField(
        _('generation prompt'),
        blank=True,
        help_text=_('Prompt used to generate this email')
    )

    # Red Flags for Learning
    red_flags = models.JSONField(
        _('red flags'),
        default=list,
        blank=True,
        help_text=_('List of phishing indicators in this email')
    )
    explanation = models.TextField(
        _('explanation'),
        blank=True,
        help_text=_('Detailed explanation of why this is/isn\'t phishing')
    )
    explanation_ar = models.TextField(
        _('explanation (Arabic)'),
        blank=True
    )

    # Metadata
    language = models.CharField(
        _('language'),
        max_length=2,
        choices=[('en', 'English'), ('ar', 'Arabic')],
        default='en'
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='created_email_templates',
        verbose_name=_('created by')
    )

    # Timestamps
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('updated at'), auto_now=True)

    class Meta:
        verbose_name = _('email template')
        verbose_name_plural = _('email templates')
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['campaign', 'email_type']),
            models.Index(fields=['email_type', 'difficulty']),
            models.Index(fields=['is_ai_generated']),
        ]

    def __str__(self):
        return f"{self.email_type}: {self.subject[:50]}"

    @property
    def is_phishing(self):
        """Check if this email is a phishing email."""
        return self.email_type == 'PHISHING'


class QuizQuestion(models.Model):
    """
    QuizQuestion model linking an email template to a specific quiz.

    Each question represents one email that the employee needs to classify
    as phishing or legitimate.
    """

    ANSWER_CHOICES = [
        ('PHISHING', _('Phishing')),
        ('LEGITIMATE', _('Legitimate')),
    ]

    # Relationships
    quiz = models.ForeignKey(
        'campaigns.Quiz',
        on_delete=models.CASCADE,
        related_name='questions',
        verbose_name=_('quiz')
    )
    email_template = models.ForeignKey(
        EmailTemplate,
        on_delete=models.CASCADE,
        related_name='quiz_questions',
        verbose_name=_('email template')
    )

    # Question Details
    question_number = models.PositiveIntegerField(
        _('question number'),
        help_text=_('Order of this question in the quiz')
    )

    # Employee Response
    answer = models.CharField(
        _('employee answer'),
        max_length=20,
        choices=ANSWER_CHOICES,
        null=True,
        blank=True
    )
    is_correct = models.BooleanField(
        _('is correct'),
        null=True,
        blank=True,
        help_text=_('Whether the employee\'s answer is correct')
    )
    confidence_level = models.PositiveIntegerField(
        _('confidence level'),
        null=True,
        blank=True,
        help_text=_('Employee confidence in their answer (1-5)')
    )

    # Timing
    time_spent_seconds = models.PositiveIntegerField(
        _('time spent (seconds)'),
        null=True,
        blank=True,
        help_text=_('Time spent on this question')
    )
    answered_at = models.DateTimeField(
        _('answered at'),
        null=True,
        blank=True
    )

    # Feedback flags
    requires_training = models.BooleanField(
        _('requires training'),
        default=False,
        help_text=_('Flag if employee needs additional training on this type')
    )

    # Timestamps
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('updated at'), auto_now=True)

    class Meta:
        verbose_name = _('quiz question')
        verbose_name_plural = _('quiz questions')
        ordering = ['quiz', 'question_number']
        unique_together = ['quiz', 'question_number']
        indexes = [
            models.Index(fields=['quiz', 'question_number']),
            models.Index(fields=['is_correct']),
        ]

    def __str__(self):
        return f"Q{self.question_number}: {self.email_template.subject[:30]}"

    def check_answer(self):
        """
        Check if the employee's answer is correct and update is_correct field.
        """
        if self.answer is None:
            self.is_correct = None
            return None

        correct_answer = 'PHISHING' if self.email_template.is_phishing else 'LEGITIMATE'
        self.is_correct = (self.answer == correct_answer)

        # Flag for training if incorrect on a phishing email
        if not self.is_correct and self.email_template.is_phishing:
            self.requires_training = True

        return self.is_correct

    @property
    def correct_answer(self):
        """Get the correct answer for this question."""
        return 'PHISHING' if self.email_template.is_phishing else 'LEGITIMATE'
